### ISSUE TITLE
Test changes from v2.4.1

### ISSUE THREAD

**Issue by BartoszChadrys** [IIS-ZPI/ZPI2023_IO1_GYM_BROS#53]

**Comment by IgorJonski** [comment]
Test results of changes from #51 

✅ - Display 'Decrease' text field with decreasing number of sessions
✅ - Display 'Growth' text field with growth number of sessions
✅ - Display 'Total' text field with total number of sessions
✅ - Total number of sessions is always sum of decrease and growth number of sessions
✅ - Text fields with number of sessions are set to '0', unless currency and period fields are selected
✅ - After changing currency or period, text fields with number of sessions are updated with new values

Result:
**6/6 PASSED**

_Main document with test scenarios has been updated to include new functionality changes._
